package com.briup.jz.dao;

import com.briup.jz.bean.Product;
import com.briup.jz.bean.ProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    long countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    List<Product> selectByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    Product selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_product
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    int updateByPrimaryKey(Product record);
}