package com.briup.jz.bean;

import java.io.Serializable;

public class Address implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_address.id
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_address.username
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_address.telephone
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_address.province
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_address.city
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_address.area
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_address.address
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jz_address.user_id
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jz_address
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_address.id
     *
     * @return the value of jz_address.id
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_address.id
     *
     * @param id the value for jz_address.id
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_address.username
     *
     * @return the value of jz_address.username
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_address.username
     *
     * @param username the value for jz_address.username
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_address.telephone
     *
     * @return the value of jz_address.telephone
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_address.telephone
     *
     * @param telephone the value for jz_address.telephone
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_address.province
     *
     * @return the value of jz_address.province
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_address.province
     *
     * @param province the value for jz_address.province
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_address.city
     *
     * @return the value of jz_address.city
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_address.city
     *
     * @param city the value for jz_address.city
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_address.area
     *
     * @return the value of jz_address.area
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_address.area
     *
     * @param area the value for jz_address.area
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_address.address
     *
     * @return the value of jz_address.address
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_address.address
     *
     * @param address the value for jz_address.address
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jz_address.user_id
     *
     * @return the value of jz_address.user_id
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jz_address.user_id
     *
     * @param userId the value for jz_address.user_id
     *
     * @mbg.generated Thu Jun 11 15:13:29 GMT+08:00 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}